### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by karelbilek** [Geremia/AquinasOperaOmnia#12]
Thanks for this.

I know you just mirror already existing website.

I just worry a bit there might be some copyright issues. I am looking primarily for Cathena Aurea, which is probably not copyrighted (the book was translated in 1874, definitely in Public Domain; I don't think the transcribing from there to text is enough of editorial work); but I am not sure.

I don't think it's, however, proper, in Catholic view, to share copyrighted books. (Of course what is copyrighted is the translation, not the Latin original).

But let's see, if someone complains / sends DMCA.

**Comment by gdweber** [comment]
The dhspriory.org/thomas site now says "Due to copyright concerns, this website is no longer hosting English translations of the works of St. Thomas Aquinas."  That suggests that this concern should be looked into.

The translation by Jean Oesterle of Peri Hermeneias, copyright 1962, seems to have fallen into the public domain in 1990, when copyright was not renewed.  I also cannot find it in the catalog of the publisher, Univ. of Notre Dame Press.

**Comment by gdweber** [comment]
> The translation by Jean Oesterle of Peri Hermeneias, copyright 1962, seems to have fallen into the public domain in 1990, when copyright was not renewed. I also cannot find it in the catalog of the publisher, Univ. of Notre Dame Press.

I'm not sure about copyright not being renewed; I was looking for renewal by Univ. of Notre Dame Press, but the publisher is Marquette University Press, and they still do have it in their catalog.

**Comment by gdweber** [comment]
Due to ethical and legal concerns, and in view of Geremia's seeming lack of interest in the copyright issues (by closing this as "not planned"), I have deleted my mirror of this repository, and will not be making any contributions as previously planned to this project.
